spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: module-tdd

resilience4j:
  retry:
    backends:
      find-cep-retry:
        maxRetryAttempts: 10
        waitDuration: 1000
        retryExceptions:
          - io.github.mrspock.moduletdd.domain.exception.TimeoutException
  circuit-breaker:
    backends:
      find-cep-circuit-breaker:
        failureRateThreshold: 100
        waitDurationInOpenState: 60s
        minimumNumberOfCalls: 90
        permittedNumberOfCallsInHalfOpenState: 10
        slidingWindowSize: 100
        ignoreExceptions:
          - io.github.mrspock.moduletdd.domain.exception.NotFoundException
          - io.github.mrspock.moduletdd.domain.exception.BadRequestException

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 5000
      via-cep:
        url: https://viacep.com.br